models:
  - name: stg__bike_data
    description: ""
    columns:
      - name: bike_id
        data_type: integer
        description: ""

      - name: ride_id
        data_type: varchar
        description: ""

      - name: rideable_type
        data_type: varchar
        description: ""

      - name: user_type
        data_type: varchar
        description: ""

      - name: birth_year
        data_type: integer
        description: ""

      - name: gender
        data_type: integer
        description: ""

      - name: trip_duration
        data_type: integer
        description: ""

      - name: start_time
        data_type: timestamp
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

      - name: stop_time
        data_type: timestamp
        description: ""

      - name: start_station_id
        data_type: integer
        description: ""

      - name: start_station_name
        data_type: varchar
        description: ""

      - name: start_station_latitude
        data_type: double
        description: ""

      - name: start_station_longitude
        data_type: double
        description: ""

      - name: end_station_id
        data_type: integer
        description: ""

      - name: end_station_name
        data_type: varchar
        description: ""

      - name: end_station_latitude
        data_type: double
        description: ""

      - name: end_station_longitude
        data_type: double
        description: ""

      - name: filename
        data_type: varchar
        description: ""

  - name: stg__central_park_weather
    description: ""
    columns:
      - name: measurement_date
        data_type: date
        description: ""

      - name: avg_wind_speed
        data_type: double
        description: ""

      - name: precipitation
        data_type: double
        description: ""

      - name: snow
        data_type: double
        description: ""

      - name: max_temp
        data_type: integer
        description: ""

      - name: min_temp
        data_type: integer
        description: ""

      - name: filename
        data_type: varchar
        description: ""

  - name: stg__fhv_bases
    description: ""
    columns:
      - name: base_id
        data_type: varchar
        description: ""

      - name: base_name
        data_type: varchar
        description: ""

      - name: dba
        data_type: varchar
        description: ""

      - name: dba_category
        data_type: varchar
        description: ""

      - name: filename
        data_type: varchar
        description: ""

  - name: stg__fhv_tripdata
    description: ""
    columns:
      - name: dispatching_base_id
        data_type: varchar
        description: ""
        tests:
          - relationships:
              to: ref('stg__fhv_bases')
              field: base_id
              config:
                    severity: warn

      - name: pickup_datetime
        data_type: timestamp
        description: ""

      - name: dropoff_datetime
        data_type: timestamp
        description: ""

      - name: pickup_location_id
        data_type: double
        description: ""

      - name: dropoff_location_id
        data_type: double
        description: ""

      - name: affiliated_base_id
        data_type: varchar
        description: ""
        tests:
          - relationships:
              to: ref('stg__fhv_bases')
              field: base_id
              config:
                    severity: warn

      - name: filename
        data_type: varchar
        description: ""

  - name: stg__fhvhv_tripdata
    description: ""
    columns:
      - name: hvfhs_license_num
        data_type: varchar
        description: ""

      - name: dispatching_base_id
        data_type: varchar
        description: ""

      - name: originating_base_id
        data_type: varchar
        description: ""

      - name: request_datetime
        data_type: timestamp
        description: ""

      - name: on_scene_datetime
        data_type: timestamp
        description: ""

      - name: pickup_datetime
        data_type: timestamp
        description: ""

      - name: dropoff_datetime
        data_type: timestamp
        description: ""

      - name: pickup_location_id
        data_type: bigint
        description: ""

      - name: dropoff_location_id
        data_type: bigint
        description: ""

      - name: trip_miles
        data_type: double
        description: ""

      - name: trip_time
        data_type: bigint
        description: ""

      - name: base_passenger_fare
        data_type: double
        description: ""

      - name: toll_charges
        data_type: double
        description: ""

      - name: black_card_funds
        data_type: double
        description: ""

      - name: sales_tax
        data_type: double
        description: ""

      - name: congestion_surcharge
        data_type: double
        description: ""

      - name: airport_fee
        data_type: double
        description: ""

      - name: tip_charges
        data_type: double
        description: ""

      - name: driver_pay
        data_type: double
        description: ""

      - name: shared_request
        data_type: boolean
        description: ""

      - name: shared_match
        data_type: boolean
        description: ""

      - name: metro_transportation
        data_type: boolean
        description: ""
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bool
              config:
                    severity: warn

      - name: wheelchair_accesible_request
        data_type: boolean
        description: ""

      - name: wheelchair_accesible_match
        data_type: boolean
        description: ""

      - name: filename
        data_type: varchar
        description: ""

  - name: stg__green_tripdata
    description: ""
    columns:
      - name: vendor_id
        data_type: bigint
        description: ""

      - name: pickup_datetime
        data_type: timestamp
        description: ""

      - name: dropoff_datetime
        data_type: timestamp
        description: ""

      - name: store_and_fwd
        data_type: boolean
        description: ""

      - name: ratecode_id
        data_type: double
        description: ""

      - name: pickup_location_id
        data_type: bigint
        description: ""

      - name: dropoff_location_id
        data_type: bigint
        description: ""

      - name: passenger_count
        data_type: double
        description: ""

      - name: trip_distance
        data_type: double
        description: ""

      - name: fare_charges
        data_type: double
        description: ""

      - name: extra_charges
        data_type: double
        description: ""

      - name: mta_tax
        data_type: double
        description: ""

      - name: tip_charges
        data_type: double
        description: ""

      - name: toll_charges
        data_type: double
        description: ""

      - name: improvement_surcharge
        data_type: double
        description: ""

      - name: total_amount
        data_type: double
        description: ""

      - name: payment_type
        data_type: double
        description: ""

      - name: trip_type
        data_type: double
        description: ""

      - name: congestion_surcharge
        data_type: double
        description: ""

      - name: filename
        data_type: varchar
        description: ""

  - name: stg__yellow_tripdata
    description: ""
    columns:
      - name: vendor_id
        data_type: bigint
        description: ""

      - name: pickup_datetime
        data_type: timestamp
        description: ""

      - name: dropoff_datetime
        data_type: timestamp
        description: ""

      - name: passenger_count
        data_type: double
        description: ""

      - name: trip_distance
        data_type: double
        description: ""

      - name: ratecode_id
        data_type: double
        description: ""

      - name: store_and_fwd
        data_type: boolean
        description: ""

      - name: pickup_location_id
        data_type: bigint
        description: ""

      - name: dropoff_location_id
        data_type: bigint
        description: ""

      - name: payment_type
        data_type: bigint
        description: ""

      - name: fare_charges
        data_type: double
        description: ""

      - name: extra_charges
        data_type: double
        description: ""

      - name: mta_tax
        data_type: double
        description: ""

      - name: tip_charges
        data_type: double
        description: ""

      - name: toll_charges
        data_type: double
        description: ""

      - name: improvement_surcharge
        data_type: double
        description: ""

      - name: total_amount
        data_type: double
        description: ""

      - name: congestion_surcharge
        data_type: double
        description: ""

      - name: airport_charges
        data_type: double
        description: ""

      - name: filename
        data_type: varchar
        description: ""